In [1]:
import numpy as np
from data_loader import load_dataset, load_challenge, save_challenge
from torch import nn
import torch
from torch.utils.data import DataLoader, Dataset
from sklearn.preprocessing import StandardScaler
from eval_script import compute_revenue

In [2]:
class BirdCrossEntropyLoss(nn.Module):
    def __init__(self, device):
        super(BirdCrossEntropyLoss, self).__init__()
        self.rev_matrix = torch.tensor(np.array(
            [[0.05, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2],
             [-0.25,  1., -0.3, -0.1, -0.1, -0.1, -0.1],
                [-0.02, -0.1,  1., -0.1, -0.1, -0.1, -0.1],
                [-0.25, -0.1, -0.3,  1., -0.1, -0.1, -0.1],
                [-0.25, -0.1, -0.3, -0.1,  1., -0.1, -0.1],
                [-0.25, -0.1, -0.3, -0.1, -0.1,  1., -0.1],
                [-0.25, -0.1, -0.3, -0.1, -0.1, -0.1,  1.]])).to(device)
        self.cet = nn.CrossEntropyLoss(reduction='none').to(device)


    def forward(self, input, target):
        ce_loss = self.cet(input, target)

        input_labels = torch.argmax(input, dim=1)
        target_labels = torch.argmax(target, dim=1)
        wanted = self.rev_matrix[target_labels, target_labels]
        actual = self.rev_matrix[target_labels, input_labels]
        cost = wanted - actual
        custom_loss = cost * ce_loss

        return custom_loss.mean()


In [3]:
class BirdDataset(Dataset):
    def __init__(self, birdset, is_train, device, offset, scaler=None):
        self.device = device
        self.offset = offset
        self.data = np.empty((0, 548), dtype=np.float32)
        self.labels = np.empty((0), dtype=int)
        for bird in birdset:
            if is_train:
                self.data = np.concatenate(
                    (self.data, np.concatenate(birdset[bird]['train_features'])))
                self.labels = np.concatenate(
                    (self.labels, np.concatenate(birdset[bird]['train_labels'])))
            else:
                self.data = np.concatenate(
                    (self.data, np.concatenate(birdset[bird]['test_features'])))
                self.labels = np.concatenate(
                    (self.labels, np.concatenate(birdset[bird]['test_labels'])))

        self.data = np.concatenate((np.zeros((offset, 548)), self.data, np.zeros((offset, 548))))

        hot_matrix = np.eye(7)
        self.labels = hot_matrix[self.labels]

        if scaler == None:
            scaler = StandardScaler()
            scaler.fit(self.data)
        self.scaler = scaler

        self.data = torch.tensor(
            self.scaler.transform(self.data), dtype=torch.float32).to(self.device)
        self.labels = torch.tensor(self.labels).to(self.device)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, index):
        x = self.data[index:index+self.offset*2+1].unsqueeze(0)
        y = self.labels[index]
        return x, y


In [4]:
def train(dataloader, model, loss_fn, optimizer, progress_steps):
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if progress_steps != None and batch % progress_steps == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(dataloader, model, loss_fn, show_progress):
    num_batches = len(dataloader)
    test_loss = 0
    money = 0
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            money += compute_revenue(torch.argmax(pred, dim=1).cpu(), torch.argmax(y, dim=1).cpu())

    test_loss /= num_batches
    if show_progress:
        print(f"Avg loss: {test_loss:>8f}, Money saved: {money:.2f}$\n")
    return test_loss

def eval(model_fn, train_dataloader, test_dataloader, device, max_epochs):
    model = model_fn(None).to(device)
    optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
    loss_fn = BirdCrossEntropyLoss(device)
    lowest_test_loss = np.infty
    stop_criterion = 0
    for t in range(max_epochs):
        if t % 10 == 0:
            print(f"Epoch {t+1}\n-------------------------------")
        train(train_dataloader, model, loss_fn, optimizer, None)
        test_loss = test(test_dataloader, model, loss_fn, True)
        if test_loss > lowest_test_loss:
            stop_criterion += 1
        else:
            lowest_test_loss = test_loss
            stop_criterion = 0
        if stop_criterion >= 10:
            break
    print("Estimated performance:")
    test(test_dataloader, model, loss_fn, True)
    return model


In [5]:
offset = 5

model_fn = lambda _: nn.Sequential(
        nn.Conv2d(1, 16, kernel_size=(3, 1), stride=1), #input = 1*11*548
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=(2, 1), stride=(2, 1)), #input = 16*9*548
        nn.Conv2d(16, 32, kernel_size=(3, 1), stride=1), #input = 16*4*548
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=(2, 1), stride=(2, 1)), #input = 32*2*548
        nn.Flatten(),
        nn.Linear(32 * 1 * 548, 64), #input = 32*3*548
        nn.ReLU(),
        nn.Linear(64, 7)
    )

class PrintDimension(nn.Module):
    def forward(self, x):
        print("Current dimension:", x.shape)
        return x

In [6]:
dataset = load_dataset()

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' 
train_set = BirdDataset(dataset, True, device, offset)
scaler = train_set.scaler
test_set = BirdDataset(dataset, False, device, offset, scaler)
train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
test_loader = DataLoader(test_set, batch_size=32, shuffle=True)

In [39]:
model = eval(model_fn, train_loader, test_loader, device, 500)

Epoch 1
-------------------------------
Avg loss: 0.118117, Money saved: 5464.55$

Avg loss: 0.133810, Money saved: 4496.86$

Avg loss: 0.090139, Money saved: 5655.99$

Avg loss: 0.102407, Money saved: 6028.48$

Avg loss: 0.100378, Money saved: 5206.64$

Avg loss: 0.081915, Money saved: 5980.05$

Avg loss: 0.084232, Money saved: 5773.87$

Avg loss: 0.076624, Money saved: 6117.06$

Avg loss: 0.080090, Money saved: 5806.75$

Avg loss: 0.090759, Money saved: 5421.19$

Epoch 11
-------------------------------
Avg loss: 0.083019, Money saved: 5770.24$

Avg loss: 0.089436, Money saved: 5559.62$

Avg loss: 0.079662, Money saved: 5735.29$

Avg loss: 0.079726, Money saved: 6051.39$

Avg loss: 0.072406, Money saved: 6179.35$

Avg loss: 0.076321, Money saved: 5918.93$

Avg loss: 0.076910, Money saved: 5858.78$

Avg loss: 0.076403, Money saved: 5859.90$

Avg loss: 0.090369, Money saved: 5435.05$

Avg loss: 0.082389, Money saved: 5590.60$

Epoch 21
-------------------------------
Avg loss: 0.080186

In [40]:
torch.save(model.state_dict(), 'cnn')

In [8]:
challenge = load_challenge()
print(challenge.shape)

(16, 3000, 548)


In [12]:
model = model_fn(None)
model.load_state_dict(torch.load('cnn'))
model.eval()

model = model.to(device)
results = torch.Tensor(np.empty((challenge.shape[0], challenge.shape[1]))).to(device)
for i in range(challenge.shape[0]):
    challenge_subset = challenge[i]
    challenge_subset = scaler.transform(challenge_subset)
    tmp = np.empty((len(challenge_subset), 11, 548))
    size = len(challenge_subset)
    challenge_subset = np.concatenate((np.zeros((offset, 548)), challenge_subset, np.zeros((offset, 548))))
    for a in range(size):
        tmp[a] = challenge_subset[a:a+offset*2+1]
    challenge_subset = torch.Tensor(tmp).unsqueeze(1).to(device)
    preds = model(challenge_subset).squeeze()
    pred_labels = torch.argmax(preds, dim=1)
    results[i, :] = pred_labels
results = results.int().cpu().numpy()
print(results, results.shape)
save_challenge('cnn', results)

[[5 5 5 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 3 3 3]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 6 6 6]
 [0 0 0 ... 0 0 0]] (16, 3000)
