In [1]:
import numpy as np
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from data_loader import _load, load_challenge, save_challenge
from sklearn.metrics import accuracy_score, classification_report

In [2]:
# Load data 
X_train, y_train, stratify_criterion, X_test, y_test, a_train, a_test = _load()
print(X_train.shape, y_train.shape, stratify_criterion.shape, X_test.shape, y_test.shape)

(96000, 548) (96000,) (96000,) (24000, 548) (24000,)


In [3]:
selected_features = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 18, 19, 21, 22, 24,
 26, 31, 32, 34, 41, 45, 46, 47, 62, 69, 73, 75, 78, 88, 99, 117, 145, 151,
 159, 174, 175, 182, 187, 197, 201, 219, 221, 224, 225, 226, 230, 231, 239, 246, 
 247, 249, 256, 257, 259, 260, 261, 262, 266, 272, 277, 285, 287, 291, 297, 302, 
 304, 319, 320, 321, 325, 327, 332, 335, 340, 347, 350, 351, 354, 366, 369, 370, 
 371, 380, 384, 387, 388, 396, 398, 399, 400, 401, 402, 405, 407, 409, 411, 412, 
 413, 415, 416, 417, 418, 419, 420, 421, 422, 424, 430, 433, 436, 440, 443, 451, 
 453, 454, 457, 463, 467, 469, 472, 478, 479, 487, 488, 490, 491, 494, 501, 505, 
 507, 539]

X_train = X_train[:, selected_features]
X_test = X_test[:, selected_features]
y_train = y_train
y_test = y_test
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(96000, 134)
(24000, 134)
(96000,)
(24000,)


In [4]:
# Now trying GridSearch,....

In [5]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto', max_iter=5000))
clf.fit(X_train, y_train)

C:\Users\Matth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:301: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto', max_iter=5000))])

In [6]:
# Evaluation
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Accuracy: 0.789875
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.89      0.88     17073
           1       0.27      0.53      0.35      1166
           2       0.74      0.55      0.63      1790
           3       0.63      0.62      0.63      1640
           4       0.84      0.49      0.62       465
           5       0.92      0.43      0.59      1022
           6       0.94      0.62      0.75       844

    accuracy                           0.79     24000
   macro avg       0.74      0.59      0.63     24000
weighted avg       0.82      0.79      0.80     24000



In [7]:
challenge = load_challenge()
challenge = challenge[:, :, selected_features]
print(challenge.shape)

(16, 3000, 134)


In [8]:
results = np.empty((challenge.shape[0], challenge.shape[1]))
for i in range(challenge.shape[0]):
    challenge_subset = challenge[i]
    pred_labels = clf.predict(challenge_subset)
    results[i, :] = pred_labels
results = results.astype(int)
print(results, results.shape)
save_challenge('svm_test', results)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 3 3 3]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 6 6 0]
 [0 0 0 ... 0 0 0]] (16, 3000)
